#!/usr/bin/env sh\n. "$(dirname -- "$0")/_/husky.sh"\n\nnpx lint-staged


# Fix Format standards
npm run format ||
(
    echo '🤢🤮🤢🤮 Your Format looks disgusting. 🤢🤮🤢🤮
            Style Fix Failed. Run npm run format, add changes and try commit again.';
    false;
)